CREATE TABLE purchases (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER,
    purchase_number VARCHAR NOT NULL UNIQUE,
    total_amount DOUBLE NOT NULL,
    payment_method VARCHAR NOT NULL DEFAULT 'CASH',
    status VARCHAR NOT NULL DEFAULT 'COMPLETED',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE purchase_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    purchase_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    unit_price DOUBLE NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal DOUBLE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (purchase_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
);
