// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BusinessInfoRequest = { name: string, county: string, phone: string, email: string, };
