// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BusinessResponse = { name: string, address: string | null, phone: string | null, email: string | null, currency: string, };
