// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateProductCategoryRequest = { parent_id: number | null, name: string, description: string | null, image: [string, Array<number>] | null, is_active: boolean, };
