// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvatarPayload } from "./AvatarPayload";

export type CreateUserRequest = { first_name: string, last_name: string, email: string, phone: string | null, password: string, mfa_enabled: boolean, mfa_method: string | null, role: number | null, avatar: AvatarPayload | null, };
