// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateProductRequest = { sku: string, item_name: string, category_id: number, cost_price: number, selling_price: number, quantity_on_hand: number, low_stock_threshold: number | null, };
