// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentMethod } from "./PaymentMethod";
import type { PurchaseItem } from "./PurchaseItem";

export type CreatePurchaseRequest = { user_id: number, payment_method: PaymentMethod, items: Array<PurchaseItem>, };
