// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BusinessInfoRequest } from "./BusinessInfoRequest";
import type { UserInfoRequest } from "./UserInfoRequest";

export type OnboardingRequest = { business: BusinessInfoRequest, admin: UserInfoRequest, };
