// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductResponse = { id: number, item_name: string, cost_price: number, selling_price: number, stock: number, low_stock_threshold: number | null, };
