// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserResponse = { id: number, first_name: string, last_name: string, email: string, phone: string | null, avatar: string | null, role: number | null, mfa_enabled: boolean, mfa_method: string | null, };
